import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { i18nConfig } from "@/app/i18n/i18n-config";
import { dir } from "i18next";
import { DefaultServerComponentProps } from "../utils/types";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({
    lang: locale,
  }));
}

export default async function RootLayout({
  children,
  params,
}: DefaultServerComponentProps<{ children: React.ReactNode }>) {
  const { lang } = await params;

  return (
    <html lang={lang} dir={dir(lang)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
